/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import clases.Cliente;
import gestion.Agencia;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bloque7
 */
public class frmClientes extends javax.swing.JFrame {

    private Agencia agencia;
    private DefaultTableModel modelo;

    /**
     * Creates new form frmClientes
     */
    public frmClientes(Agencia agencia) {
        this.agencia = agencia;
        initComponents();
        modelo = new DefaultTableModel(new String[]{"Documento", "Nombres", "Apellidos",
            "F. Nacimiento", "Nacionalidad", "Telefono", "Correo", "Puntos"}, 0);
        tblClientes.setModel(modelo);
        setSize(860, 520);
        setLocationRelativeTo(null);
        listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDatos = new javax.swing.JPanel();
        lblDocumento = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        lblNombres = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        lblApellidos = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        lblFechaNacimiento = new javax.swing.JLabel();
        txtFechaNacimiento = new javax.swing.JTextField();
        lblNacionalidad = new javax.swing.JLabel();
        txtNacionalidad = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        scrTabla = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        pnlBotones = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(".: Mantenimiento de Clientes :.");

        getContentPane().setLayout(new java.awt.BorderLayout());

        pnlDatos.setLayout(new java.awt.GridLayout(7, 2));
        lblDocumento.setText("DNI o Pasaporte:");
        pnlDatos.add(lblDocumento);

        pnlDatos.add(txtDocumento);

        lblNombres.setText("Nombres:");
        pnlDatos.add(lblNombres);

        pnlDatos.add(txtNombres);

        lblApellidos.setText("Apellidos:");
        pnlDatos.add(lblApellidos);

        pnlDatos.add(txtApellidos);

        lblFechaNacimiento.setText("Fecha de nacimiento (dd/mm/aaaa):");
        pnlDatos.add(lblFechaNacimiento);

        pnlDatos.add(txtFechaNacimiento);

        lblNacionalidad.setText("Nacionalidad:");
        pnlDatos.add(lblNacionalidad);

        pnlDatos.add(txtNacionalidad);

        lblTelefono.setText("Telefono:");
        pnlDatos.add(lblTelefono);

        pnlDatos.add(txtTelefono);

        lblCorreo.setText("Correo electronico:");
        pnlDatos.add(lblCorreo);

        pnlDatos.add(txtCorreo);

        getContentPane().add(pnlDatos, java.awt.BorderLayout.NORTH);

        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        scrTabla.setViewportView(tblClientes);

        getContentPane().add(scrTabla, java.awt.BorderLayout.CENTER);

        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vcsnormal.png"))); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);
        pnlBotones.add(btnRegistrar);

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/edit.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(this::btnModificarActionPerformed);
        pnlBotones.add(btnModificar);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/delete_remove.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);
        pnlBotones.add(btnEliminar);

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/update_rotation.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);
        pnlBotones.add(btnLimpiar);

        getContentPane().add(pnlBotones, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        registrar();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        modificar();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked
        int fila = tblClientes.getSelectedRow();
        if (fila >= 0) {
            txtDocumento.setText(modelo.getValueAt(fila, 0).toString());
            txtNombres.setText(modelo.getValueAt(fila, 1).toString());
            txtApellidos.setText(modelo.getValueAt(fila, 2).toString());
            txtFechaNacimiento.setText(modelo.getValueAt(fila, 3).toString());
            txtNacionalidad.setText(modelo.getValueAt(fila, 4).toString());
            txtTelefono.setText(modelo.getValueAt(fila, 5).toString());
            txtCorreo.setText(modelo.getValueAt(fila, 6).toString());
        }
    }//GEN-LAST:event_tblClientesMouseClicked

    private Cliente construirCliente() {
        return new Cliente(txtDocumento.getText().trim(), txtNombres.getText().trim(),
                txtApellidos.getText().trim(), txtFechaNacimiento.getText().trim(),
                txtNacionalidad.getText().trim(), txtTelefono.getText().trim(),
                txtCorreo.getText().trim());
    }

    private void registrar() {
        if (txtDocumento.getText().trim().equals("") || txtNombres.getText().trim().equals("")
                || txtApellidos.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Complete documento, nombres y apellidos");
            return;
        }
        if (agencia.getGestionCliente().registrar(construirCliente())) {
            JOptionPane.showMessageDialog(this, "Cliente registrado correctamente");
            listar();
            limpiar();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo registrar (documento duplicado)");
        }
    }

    private void modificar() {
        if (agencia.getGestionCliente().actualizar(construirCliente())) {
            JOptionPane.showMessageDialog(this, "Cliente modificado correctamente");
            listar();
            limpiar();
        } else {
            JOptionPane.showMessageDialog(this, "No se encontro el cliente");
        }
    }

    private void eliminar() {
        if (agencia.getGestionCliente().eliminar(txtDocumento.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Cliente eliminado");
            listar();
            limpiar();
        } else {
            JOptionPane.showMessageDialog(this, "No se encontro el cliente");
        }
    }

    private void limpiar() {
        txtDocumento.setText("");
        txtNombres.setText("");
        txtApellidos.setText("");
        txtFechaNacimiento.setText("");
        txtNacionalidad.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");
        tblClientes.clearSelection();
    }

    private void listar() {
        modelo.setRowCount(0);
        Cliente[] clientes = agencia.getGestionCliente().obtenerClientes();
        int total = agencia.getGestionCliente().obtenerTotalClientes();
        for (int i = 0; i < total; i++) {
            modelo.addRow(new Object[]{clientes[i].getDni(), clientes[i].getNombres(),
                clientes[i].getApellidos(), clientes[i].getFechaNacimiento(),
                clientes[i].getNacionalidad(), clientes[i].getTelefono(),
                clientes[i].getCorreo(), clientes[i].obtenerPuntos()});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JLabel lblDocumento;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JLabel lblNacionalidad;
    private javax.swing.JTextField txtNacionalidad;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JScrollPane scrTabla;
    private javax.swing.JTable tblClientes;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    // End of variables declaration//GEN-END:variables
}
