/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import clases.DestinoTuristico;
import gestion.Agencia;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bloque7
 */
public class frmDestinos extends javax.swing.JFrame {

    private Agencia agencia;
    private DefaultTableModel modelo;

    /**
     * Creates new form frmDestinos
     */
    public frmDestinos(Agencia agencia) {
        this.agencia = agencia;
        initComponents();
        modelo = new DefaultTableModel(
                new String[]{"Nombre", "Pais", "Ciudad", "Descripcion", "Clima", "Idioma", "Imagen"}, 0);
        tblDestinos.setModel(modelo);
        setSize(820, 520);
        setLocationRelativeTo(null);
        listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDatos = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblPais = new javax.swing.JLabel();
        txtPais = new javax.swing.JTextField();
        lblCiudad = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        lblClima = new javax.swing.JLabel();
        txtClima = new javax.swing.JTextField();
        lblIdioma = new javax.swing.JLabel();
        txtIdioma = new javax.swing.JTextField();
        lblRutaImagen = new javax.swing.JLabel();
        txtRutaImagen = new javax.swing.JTextField();
        scrTabla = new javax.swing.JScrollPane();
        tblDestinos = new javax.swing.JTable();
        pnlBotones = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(".: Mantenimiento de Destinos Turisticos :.");

        getContentPane().setLayout(new java.awt.BorderLayout());

        pnlDatos.setLayout(new java.awt.GridLayout(7, 2));
        lblNombre.setText("Nombre:");
        pnlDatos.add(lblNombre);

        pnlDatos.add(txtNombre);

        lblPais.setText("Pais:");
        pnlDatos.add(lblPais);

        pnlDatos.add(txtPais);

        lblCiudad.setText("Ciudad:");
        pnlDatos.add(lblCiudad);

        pnlDatos.add(txtCiudad);

        lblDescripcion.setText("Descripcion:");
        pnlDatos.add(lblDescripcion);

        pnlDatos.add(txtDescripcion);

        lblClima.setText("Clima:");
        pnlDatos.add(lblClima);

        pnlDatos.add(txtClima);

        lblIdioma.setText("Idioma principal:");
        pnlDatos.add(lblIdioma);

        pnlDatos.add(txtIdioma);

        lblRutaImagen.setText("Imagen (ruta de archivo):");
        pnlDatos.add(lblRutaImagen);

        pnlDatos.add(txtRutaImagen);

        getContentPane().add(pnlDatos, java.awt.BorderLayout.NORTH);

        tblDestinos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDestinosMouseClicked(evt);
            }
        });
        scrTabla.setViewportView(tblDestinos);

        getContentPane().add(scrTabla, java.awt.BorderLayout.CENTER);

        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vcsnormal.png"))); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);
        pnlBotones.add(btnRegistrar);

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/edit.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(this::btnModificarActionPerformed);
        pnlBotones.add(btnModificar);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/delete_remove.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);
        pnlBotones.add(btnEliminar);

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/update_rotation.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);
        pnlBotones.add(btnLimpiar);

        getContentPane().add(pnlBotones, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        registrar();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        modificar();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tblDestinosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDestinosMouseClicked
        int fila = tblDestinos.getSelectedRow();
        if (fila >= 0) {
            txtNombre.setText(modelo.getValueAt(fila, 0).toString());
            txtPais.setText(modelo.getValueAt(fila, 1).toString());
            txtCiudad.setText(modelo.getValueAt(fila, 2).toString());
            txtDescripcion.setText(modelo.getValueAt(fila, 3).toString());
            txtClima.setText(modelo.getValueAt(fila, 4).toString());
            txtIdioma.setText(modelo.getValueAt(fila, 5).toString());
            txtRutaImagen.setText(modelo.getValueAt(fila, 6).toString());
        }
    }//GEN-LAST:event_tblDestinosMouseClicked

    private DestinoTuristico construirDestino() {
        return new DestinoTuristico(txtNombre.getText().trim(), txtPais.getText().trim(),
                txtCiudad.getText().trim(), txtDescripcion.getText().trim(),
                txtClima.getText().trim(), txtIdioma.getText().trim(), txtRutaImagen.getText().trim());
    }

    private void registrar() {
        if (txtNombre.getText().trim().equals("") || txtPais.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese al menos nombre y pais");
            return;
        }
        if (agencia.getGestionDestino().registrar(construirDestino())) {
            JOptionPane.showMessageDialog(this, "Destino registrado correctamente");
            listar();
            limpiar();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo registrar (nombre duplicado)");
        }
    }

    private void modificar() {
        if (agencia.getGestionDestino().actualizar(construirDestino())) {
            JOptionPane.showMessageDialog(this, "Destino modificado correctamente");
            listar();
            limpiar();
        } else {
            JOptionPane.showMessageDialog(this, "No se encontro el destino");
        }
    }

    private void eliminar() {
        if (agencia.getGestionDestino().eliminar(txtNombre.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Destino eliminado");
            listar();
            limpiar();
        } else {
            JOptionPane.showMessageDialog(this, "No se encontro el destino");
        }
    }

    private void limpiar() {
        txtNombre.setText("");
        txtPais.setText("");
        txtCiudad.setText("");
        txtDescripcion.setText("");
        txtClima.setText("");
        txtIdioma.setText("");
        txtRutaImagen.setText("");
        tblDestinos.clearSelection();
    }

    private void listar() {
        modelo.setRowCount(0);
        DestinoTuristico[] destinos = agencia.getGestionDestino().obtenerDestinos();
        int total = agencia.getGestionDestino().obtenerTotalDestinos();
        for (int i = 0; i < total; i++) {
            modelo.addRow(new Object[]{destinos[i].getNombre(), destinos[i].getPais(),
                destinos[i].getCiudad(), destinos[i].getDescripcion(), destinos[i].getClima(),
                destinos[i].getIdioma(), destinos[i].getRutaImagen()});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JLabel lblPais;
    private javax.swing.JTextField txtPais;
    private javax.swing.JLabel lblCiudad;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JLabel lblClima;
    private javax.swing.JTextField txtClima;
    private javax.swing.JLabel lblIdioma;
    private javax.swing.JTextField txtIdioma;
    private javax.swing.JLabel lblRutaImagen;
    private javax.swing.JTextField txtRutaImagen;
    private javax.swing.JScrollPane scrTabla;
    private javax.swing.JTable tblDestinos;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    // End of variables declaration//GEN-END:variables
}
