/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import clases.Administrador;
import clases.AsesorViaje;
import clases.Empleado;
import clases.Operador;
import gestion.Agencia;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bloque7
 */
public class frmEmpleados extends javax.swing.JFrame {

    private Agencia agencia;
    private DefaultTableModel modelo;

    /**
     * Creates new form frmEmpleados
     */
    public frmEmpleados(Agencia agencia) {
        this.agencia = agencia;
        initComponents();
        cboRol.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[]{"Administrador", "Asesor de Viaje", "Operador"}));
        modelo = new DefaultTableModel(
                new String[]{"DNI", "Nombres", "Apellidos", "Usuario", "Rol"}, 0);
        tblEmpleados.setModel(modelo);
        setSize(700, 480);
        setLocationRelativeTo(null);
        listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDatos = new javax.swing.JPanel();
        lblDni = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        lblNombres = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        lblApellidos = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblContrasenia = new javax.swing.JLabel();
        txtContrasenia = new javax.swing.JTextField();
        lblRol = new javax.swing.JLabel();
        cboRol = new javax.swing.JComboBox<>();
        scrTabla = new javax.swing.JScrollPane();
        tblEmpleados = new javax.swing.JTable();
        pnlBotones = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(".: Mantenimiento de Empleados :.");

        getContentPane().setLayout(new java.awt.BorderLayout());

        pnlDatos.setLayout(new java.awt.GridLayout(6, 2));
        lblDni.setText("DNI:");
        pnlDatos.add(lblDni);

        pnlDatos.add(txtDni);

        lblNombres.setText("Nombres:");
        pnlDatos.add(lblNombres);

        pnlDatos.add(txtNombres);

        lblApellidos.setText("Apellidos:");
        pnlDatos.add(lblApellidos);

        pnlDatos.add(txtApellidos);

        lblUsuario.setText("Usuario:");
        pnlDatos.add(lblUsuario);

        pnlDatos.add(txtUsuario);

        lblContrasenia.setText("Contrasena:");
        pnlDatos.add(lblContrasenia);

        pnlDatos.add(txtContrasenia);

        lblRol.setText("Rol:");
        pnlDatos.add(lblRol);

        pnlDatos.add(cboRol);

        getContentPane().add(pnlDatos, java.awt.BorderLayout.NORTH);

        tblEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmpleadosMouseClicked(evt);
            }
        });
        scrTabla.setViewportView(tblEmpleados);

        getContentPane().add(scrTabla, java.awt.BorderLayout.CENTER);

        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vcsnormal.png"))); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);
        pnlBotones.add(btnRegistrar);

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/edit.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(this::btnModificarActionPerformed);
        pnlBotones.add(btnModificar);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/delete_remove.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);
        pnlBotones.add(btnEliminar);

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/update_rotation.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);
        pnlBotones.add(btnLimpiar);

        getContentPane().add(pnlBotones, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        registrar();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        modificar();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tblEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpleadosMouseClicked
        int fila = tblEmpleados.getSelectedRow();
        if (fila >= 0) {
            txtDni.setText(modelo.getValueAt(fila, 0).toString());
            txtNombres.setText(modelo.getValueAt(fila, 1).toString());
            txtApellidos.setText(modelo.getValueAt(fila, 2).toString());
            txtUsuario.setText(modelo.getValueAt(fila, 3).toString());
            cboRol.setSelectedItem(modelo.getValueAt(fila, 4).toString());
        }
    }//GEN-LAST:event_tblEmpleadosMouseClicked

    private boolean validarCampos() {
        if (txtDni.getText().trim().equals("") || txtNombres.getText().trim().equals("")
                || txtApellidos.getText().trim().equals("") || txtUsuario.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos");
            return false;
        }
        return true;
    }

    private void registrar() {
        if (!validarCampos() || txtContrasenia.getText().trim().equals("")) {
            if (txtContrasenia.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Ingrese la contrasena");
            }
            return;
        }
        String rol = cboRol.getSelectedItem().toString();
        Empleado empleado;
        if (rol.equals("Administrador")) {
            empleado = new Administrador(txtDni.getText().trim(), txtNombres.getText().trim(),
                    txtApellidos.getText().trim(), txtUsuario.getText().trim(), txtContrasenia.getText().trim());
        } else if (rol.equals("Asesor de Viaje")) {
            empleado = new AsesorViaje(txtDni.getText().trim(), txtNombres.getText().trim(),
                    txtApellidos.getText().trim(), txtUsuario.getText().trim(), txtContrasenia.getText().trim());
        } else {
            empleado = new Operador(txtDni.getText().trim(), txtNombres.getText().trim(),
                    txtApellidos.getText().trim(), txtUsuario.getText().trim(), txtContrasenia.getText().trim());
        }
        if (agencia.getGestionEmpleado().registrar(empleado)) {
            JOptionPane.showMessageDialog(this, "Empleado registrado correctamente");
            listar();
            limpiar();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo registrar (DNI o usuario duplicado)");
        }
    }

    private void modificar() {
        if (!validarCampos()) {
            return;
        }
        String contrasenia = txtContrasenia.getText().trim();
        Empleado actual = agencia.getGestionEmpleado().buscar(txtDni.getText().trim());
        if (actual != null && contrasenia.equals("")) {
            contrasenia = actual.getContrasenia();
        }
        if (agencia.getGestionEmpleado().actualizar(txtDni.getText().trim(),
                txtNombres.getText().trim(), txtApellidos.getText().trim(),
                txtUsuario.getText().trim(), contrasenia,
                cboRol.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(this, "Empleado modificado correctamente");
            listar();
            limpiar();
        } else {
            JOptionPane.showMessageDialog(this, "No se encontro el empleado");
        }
    }

    private void eliminar() {
        if (txtDni.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Seleccione un empleado");
            return;
        }
        if (agencia.getGestionEmpleado().eliminar(txtDni.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Empleado eliminado");
            listar();
            limpiar();
        } else {
            JOptionPane.showMessageDialog(this, "No se encontro el empleado");
        }
    }

    private void limpiar() {
        txtDni.setText("");
        txtNombres.setText("");
        txtApellidos.setText("");
        txtUsuario.setText("");
        txtContrasenia.setText("");
        tblEmpleados.clearSelection();
    }

    private void listar() {
        modelo.setRowCount(0);
        Empleado[] empleados = agencia.getGestionEmpleado().obtenerEmpleados();
        int total = agencia.getGestionEmpleado().obtenerTotalEmpleados();
        for (int i = 0; i < total; i++) {
            modelo.addRow(new Object[]{empleados[i].getDni(), empleados[i].getNombres(),
                empleados[i].getApellidos(), empleados[i].getUsuario(), empleados[i].obtenerRol()});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JLabel lblDni;
    private javax.swing.JTextField txtDni;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JTextField txtContrasenia;
    private javax.swing.JLabel lblRol;
    private javax.swing.JComboBox<String> cboRol;
    private javax.swing.JScrollPane scrTabla;
    private javax.swing.JTable tblEmpleados;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    // End of variables declaration//GEN-END:variables
}
