/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import clases.ItinerarioDia;
import clases.PaqueteTuristico;
import gestion.Agencia;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bloque7
 */
public class frmItinerarios extends javax.swing.JFrame {

    private Agencia agencia;
    private DefaultTableModel modelo;

    /**
     * Creates new form frmItinerarios
     */
    public frmItinerarios(Agencia agencia) {
        this.agencia = agencia;
        initComponents();
        txtDetalle.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 13));
        modelo = new DefaultTableModel(new String[]{"Codigo", "Paquete", "Destinos", "Salida",
            "Retorno", "Cupo Disponible", "Cupo Maximo", "Estado"}, 0);
        tblPaquetes.setModel(modelo);
        setSize(880, 560);
        setLocationRelativeTo(null);
        listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrTabla = new javax.swing.JScrollPane();
        tblPaquetes = new javax.swing.JTable();
        pnlDetalle = new javax.swing.JPanel();
        lblItinerario = new javax.swing.JLabel();
        scrDetalle = new javax.swing.JScrollPane();
        txtDetalle = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(".: Consulta de Itinerarios y Cupos :.");

        getContentPane().setLayout(new java.awt.BorderLayout());

        tblPaquetes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPaquetesMouseClicked(evt);
            }
        });
        scrTabla.setViewportView(tblPaquetes);

        getContentPane().add(scrTabla, java.awt.BorderLayout.CENTER);

        pnlDetalle.setLayout(new java.awt.BorderLayout());
        lblItinerario.setText("Itinerario del paquete seleccionado:");
        pnlDetalle.add(lblItinerario, java.awt.BorderLayout.NORTH);

        scrDetalle.setPreferredSize(new java.awt.Dimension(840, 180));
        txtDetalle.setEditable(false);
        txtDetalle.setRows(8);
        scrDetalle.setViewportView(txtDetalle);

        pnlDetalle.add(scrDetalle, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlDetalle, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblPaquetesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPaquetesMouseClicked
        mostrarItinerario();
    }//GEN-LAST:event_tblPaquetesMouseClicked

    private void listar() {
        modelo.setRowCount(0);
        PaqueteTuristico[] paquetes = agencia.getGestionPaquete().obtenerPaquetes();
        int total = agencia.getGestionPaquete().obtenerTotalPaquetes();
        for (int i = 0; i < total; i++) {
            PaqueteTuristico p = paquetes[i];
            modelo.addRow(new Object[]{p.getCodigo(), p.getNombre(), p.obtenerNombresDestinos(),
                p.getFechaSalida(), p.getFechaRetorno(), p.getCupoDisponible(),
                p.getCupoMaximo(), p.getEstado()});
        }
    }

    private void mostrarItinerario() {
        int fila = tblPaquetes.getSelectedRow();
        if (fila < 0) {
            return;
        }
        PaqueteTuristico paquete = agencia.getGestionPaquete()
                .buscar(modelo.getValueAt(fila, 0).toString());
        if (paquete == null) {
            return;
        }
        String texto = "ITINERARIO - " + paquete.getNombre() + "\n";
        texto = texto + "------------------------------------------\n";
        ItinerarioDia[] itinerario = paquete.obtenerItinerario();
        for (int i = 0; i < paquete.obtenerTotalDiasItinerario(); i++) {
            texto = texto + "Dia " + itinerario[i].getDia() + ": " + itinerario[i].getDescripcion() + "\n";
        }
        if (paquete.obtenerTotalDiasItinerario() == 0) {
            texto = texto + "Este paquete aun no tiene itinerario registrado.\n";
        }
        txtDetalle.setText(texto);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrTabla;
    private javax.swing.JTable tblPaquetes;
    private javax.swing.JPanel pnlDetalle;
    private javax.swing.JLabel lblItinerario;
    private javax.swing.JScrollPane scrDetalle;
    private javax.swing.JTextArea txtDetalle;
    // End of variables declaration//GEN-END:variables
}
