/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import clases.Empleado;
import gestion.Agencia;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Bloque7
 */
public class frmLogin extends javax.swing.JFrame {

    private Agencia agencia;

    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        agencia = new Agencia();
        initComponents();
        lblTitulo.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16));
        setSize(480, 260);
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        pnlCampos = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblContrasenia = new javax.swing.JLabel();
        txtContrasenia = new javax.swing.JPasswordField();
        pnlBotones = new javax.swing.JPanel();
        btnIngresar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(".: ULIMA TRAVEL - Autenticacion de Usuario :.");

        getContentPane().setLayout(new java.awt.BorderLayout());

        lblTitulo.setText("ULIMA TRAVEL - Sistema de Reservas");
        lblTitulo.setHorizontalAlignment(0);
        getContentPane().add(lblTitulo, java.awt.BorderLayout.NORTH);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoAgencia.png"))); // NOI18N
        lblLogo.setHorizontalAlignment(0);
        getContentPane().add(lblLogo, java.awt.BorderLayout.WEST);

        pnlCampos.setLayout(new java.awt.GridLayout(2, 2));
        lblUsuario.setText("Usuario:");
        pnlCampos.add(lblUsuario);

        pnlCampos.add(txtUsuario);

        lblContrasenia.setText("Contrasena:");
        pnlCampos.add(lblContrasenia);

        pnlCampos.add(txtContrasenia);

        getContentPane().add(pnlCampos, java.awt.BorderLayout.CENTER);

        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vcsnormal.png"))); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(this::btnIngresarActionPerformed);
        pnlBotones.add(btnIngresar);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        pnlBotones.add(btnCancelar);

        getContentPane().add(pnlBotones, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        if (txtUsuario.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese el usuario");
            txtUsuario.requestFocus();
            return;
        }
        String contrasenia = new String(txtContrasenia.getPassword());
        if (contrasenia.trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese la contrasena");
            txtContrasenia.requestFocus();
            return;
        }
        Empleado empleado = agencia.getGestionEmpleado().validarLogin(
                txtUsuario.getText().trim(), contrasenia.trim());
        if (empleado == null) {
            JOptionPane.showMessageDialog(this, "Usuario o contrasena incorrectos");
            txtContrasenia.setText("");
            return;
        }
        JOptionPane.showMessageDialog(this, "Bienvenido(a) " + empleado.obtenerNombreCompleto()
                + "\nRol: " + empleado.obtenerRol()
                + "\n" + empleado.obtenerDescripcionPermisos());
        frmPrincipal principal = new frmPrincipal(agencia, empleado);
        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCancelarActionPerformed

    public static void main(String[] args) {
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception e) {
        }
        java.awt.EventQueue.invokeLater(() -> new frmLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPanel pnlCampos;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnCancelar;
    // End of variables declaration//GEN-END:variables
}
