/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import clases.Pago;
import clases.Reserva;
import gestion.Agencia;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bloque7
 */
public class frmPagos extends javax.swing.JFrame {

    private Agencia agencia;
    private DefaultTableModel modelo;

    /**
     * Creates new form frmPagos
     */
    public frmPagos(Agencia agencia) {
        this.agencia = agencia;
        initComponents();
        lblEstadoValor.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        cboMetodo.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[]{"Efectivo", "Tarjeta", "Transferencia"}));
        modelo = new DefaultTableModel(new String[]{"Fecha", "Monto", "Metodo"}, 0);
        tblPagos.setModel(modelo);
        setSize(700, 520);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDatos = new javax.swing.JPanel();
        lblCodigoReserva = new javax.swing.JLabel();
        pnlBusqueda = new javax.swing.JPanel();
        txtCodigoReserva = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblEstado = new javax.swing.JLabel();
        lblEstadoValor = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblTotalValor = new javax.swing.JLabel();
        lblPagado = new javax.swing.JLabel();
        lblPagadoValor = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        lblSaldoValor = new javax.swing.JLabel();
        lblMonto = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        lblMetodo = new javax.swing.JLabel();
        cboMetodo = new javax.swing.JComboBox<>();
        scrTabla = new javax.swing.JScrollPane();
        tblPagos = new javax.swing.JTable();
        pnlBotones = new javax.swing.JPanel();
        btnPagar = new javax.swing.JButton();
        btnVoucher = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(".: Gestion de Pagos :.");

        getContentPane().setLayout(new java.awt.BorderLayout());

        pnlDatos.setLayout(new java.awt.GridLayout(7, 2));
        lblCodigoReserva.setText("Codigo de reserva:");
        pnlDatos.add(lblCodigoReserva);

        pnlBusqueda.setLayout(new java.awt.GridLayout(1, 2));
        pnlBusqueda.add(txtCodigoReserva);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);
        pnlBusqueda.add(btnBuscar);

        pnlDatos.add(pnlBusqueda);

        lblEstado.setText("Estado:");
        pnlDatos.add(lblEstado);

        lblEstadoValor.setText("-");
        pnlDatos.add(lblEstadoValor);

        lblTotal.setText("Precio total:");
        pnlDatos.add(lblTotal);

        lblTotalValor.setText("-");
        pnlDatos.add(lblTotalValor);

        lblPagado.setText("Monto abonado:");
        pnlDatos.add(lblPagado);

        lblPagadoValor.setText("-");
        pnlDatos.add(lblPagadoValor);

        lblSaldo.setText("Saldo pendiente:");
        pnlDatos.add(lblSaldo);

        lblSaldoValor.setText("-");
        pnlDatos.add(lblSaldoValor);

        lblMonto.setText("Monto a pagar:");
        pnlDatos.add(lblMonto);

        pnlDatos.add(txtMonto);

        lblMetodo.setText("Metodo de pago:");
        pnlDatos.add(lblMetodo);

        pnlDatos.add(cboMetodo);

        getContentPane().add(pnlDatos, java.awt.BorderLayout.NORTH);

        scrTabla.setViewportView(tblPagos);

        getContentPane().add(scrTabla, java.awt.BorderLayout.CENTER);

        btnPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vcsnormal.png"))); // NOI18N
        btnPagar.setText("Registrar Pago");
        btnPagar.addActionListener(this::btnPagarActionPerformed);
        pnlBotones.add(btnPagar);

        btnVoucher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporte.png"))); // NOI18N
        btnVoucher.setText("Ver Voucher");
        btnVoucher.addActionListener(this::btnVoucherActionPerformed);
        pnlBotones.add(btnVoucher);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/delete_remove.png"))); // NOI18N
        btnCancelar.setText("Cancelar Reserva");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        pnlBotones.add(btnCancelar);

        getContentPane().add(pnlBotones, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarReserva();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        registrarPago();
    }//GEN-LAST:event_btnPagarActionPerformed

    private void btnVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoucherActionPerformed
        verVoucher();
    }//GEN-LAST:event_btnVoucherActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cancelarReserva();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private Reserva obtenerReserva() {
        return agencia.getGestionReserva().buscar(txtCodigoReserva.getText().trim());
    }

    private void buscarReserva() {
        Reserva reserva = obtenerReserva();
        if (reserva == null) {
            JOptionPane.showMessageDialog(this, "No se encontro la reserva");
            return;
        }
        actualizarDatos(reserva);
    }

    private void actualizarDatos(Reserva reserva) {
        lblEstadoValor.setText(reserva.getEstado());
        lblTotalValor.setText("S/ " + String.format("%.2f", reserva.calcularPrecioTotal()));
        lblPagadoValor.setText("S/ " + String.format("%.2f", reserva.calcularTotalPagado()));
        lblSaldoValor.setText("S/ " + String.format("%.2f", reserva.calcularSaldoPendiente())
                + "  (pago minimo para confirmar: S/ "
                + String.format("%.2f", reserva.calcularPagoMinimo()) + ")");
        modelo.setRowCount(0);
        Pago[] pagos = reserva.obtenerPagos();
        for (int i = 0; i < reserva.obtenerTotalPagos(); i++) {
            modelo.addRow(new Object[]{pagos[i].getFecha(),
                "S/ " + String.format("%.2f", pagos[i].getMonto()), pagos[i].getMetodo()});
        }
    }

    private void registrarPago() {
        Reserva reserva = obtenerReserva();
        if (reserva == null) {
            JOptionPane.showMessageDialog(this, "Busque primero una reserva valida");
            return;
        }
        double monto;
        try {
            monto = Double.parseDouble(txtMonto.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El monto debe ser numerico");
            return;
        }
        String fechaHoy = LocalDate.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        Pago pago = new Pago(fechaHoy, monto, cboMetodo.getSelectedItem().toString());
        if (agencia.getGestionReserva().registrarPago(reserva.getCodigo(), pago)) {
            JOptionPane.showMessageDialog(this, "Pago registrado. Estado de la reserva: " + reserva.getEstado());
            txtMonto.setText("");
            actualizarDatos(reserva);
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo registrar el pago (verifique el monto y el saldo)");
        }
    }

    private void verVoucher() {
        Reserva reserva = obtenerReserva();
        if (reserva == null) {
            JOptionPane.showMessageDialog(this, "Busque primero una reserva valida");
            return;
        }
        javax.swing.JTextArea area = new javax.swing.JTextArea(reserva.generarVoucher());
        area.setEditable(false);
        area.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 12));
        javax.swing.JScrollPane scroll = new javax.swing.JScrollPane(area);
        scroll.setPreferredSize(new java.awt.Dimension(480, 420));
        JOptionPane.showMessageDialog(this, scroll, "Voucher de Reserva", JOptionPane.INFORMATION_MESSAGE);
    }

    private void cancelarReserva() {
        Reserva reserva = obtenerReserva();
        if (reserva == null) {
            JOptionPane.showMessageDialog(this, "Busque primero una reserva valida");
            return;
        }
        int opcion = JOptionPane.showConfirmDialog(this,
                "Esta seguro de cancelar la reserva " + reserva.getCodigo() + "?",
                "Confirmar", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            if (agencia.getGestionReserva().cancelarReserva(reserva.getCodigo())) {
                JOptionPane.showMessageDialog(this, "Reserva cancelada y cupos liberados");
                actualizarDatos(reserva);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JLabel lblCodigoReserva;
    private javax.swing.JPanel pnlBusqueda;
    private javax.swing.JTextField txtCodigoReserva;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblEstadoValor;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalValor;
    private javax.swing.JLabel lblPagado;
    private javax.swing.JLabel lblPagadoValor;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblSaldoValor;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JLabel lblMetodo;
    private javax.swing.JComboBox<String> cboMetodo;
    private javax.swing.JScrollPane scrTabla;
    private javax.swing.JTable tblPagos;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JButton btnPagar;
    private javax.swing.JButton btnVoucher;
    private javax.swing.JButton btnCancelar;
    // End of variables declaration//GEN-END:variables
}
