/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import clases.DestinoTuristico;
import clases.ItinerarioDia;
import clases.PaqueteTuristico;
import clases.ServicioIncluido;
import gestion.Agencia;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bloque7
 */
public class frmPaquetes extends javax.swing.JFrame {

    private Agencia agencia;
    private DefaultTableModel modeloPaquetes;
    private DefaultTableModel modeloServicios;
    private DefaultTableModel modeloItinerario;

    /**
     * Creates new form frmPaquetes
     */
    public frmPaquetes(Agencia agencia) {
        this.agencia = agencia;
        initComponents();
        cboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[]{"Nacional", "Internacional", "Aventura", "Relax", "Cultural"}));
        cboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[]{"Activo", "Agotado", "Cancelado"}));
        cboTipoServicio.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[]{"Vuelo", "Hotel", "Traslado", "Visita guiada",
                    "Seguro de viaje", "Alimentacion", "Otro"}));
        cargarDestinos();
        modeloPaquetes = new DefaultTableModel(new String[]{"Codigo", "Nombre", "Destinos", "Duracion",
            "Tipo", "Precio", "Salida", "Retorno", "Cupo Disp.", "Estado"}, 0);
        tblPaquetes.setModel(modeloPaquetes);
        modeloServicios = new DefaultTableModel(new String[]{"Tipo", "Descripcion"}, 0);
        tblServicios.setModel(modeloServicios);
        modeloItinerario = new DefaultTableModel(new String[]{"Dia", "Actividades"}, 0);
        tblItinerario.setModel(modeloItinerario);
        setSize(950, 580);
        setLocationRelativeTo(null);
        listarPaquetes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPaquetes = new javax.swing.JTabbedPane();
        pnlDatosPaquete = new javax.swing.JPanel();
        pnlCamposPaquete = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblDias = new javax.swing.JLabel();
        txtDias = new javax.swing.JTextField();
        lblNoches = new javax.swing.JLabel();
        txtNoches = new javax.swing.JTextField();
        lblTipo = new javax.swing.JLabel();
        cboTipo = new javax.swing.JComboBox<>();
        lblPrecio = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        lblFechaSalida = new javax.swing.JLabel();
        txtFechaSalida = new javax.swing.JTextField();
        lblFechaRetorno = new javax.swing.JLabel();
        txtFechaRetorno = new javax.swing.JTextField();
        lblCupo = new javax.swing.JLabel();
        txtCupo = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        cboEstado = new javax.swing.JComboBox<>();
        lblDestino = new javax.swing.JLabel();
        cboDestino = new javax.swing.JComboBox<>();
        scrPaquetes = new javax.swing.JScrollPane();
        tblPaquetes = new javax.swing.JTable();
        pnlBotonesPaquete = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnAgregarDestino = new javax.swing.JButton();
        btnQuitarDestino = new javax.swing.JButton();
        pnlServicios = new javax.swing.JPanel();
        pnlCamposServicio = new javax.swing.JPanel();
        lblCodigoServicio = new javax.swing.JLabel();
        txtCodigoServicio = new javax.swing.JTextField();
        lblTipoServicio = new javax.swing.JLabel();
        cboTipoServicio = new javax.swing.JComboBox<>();
        lblDescripcionServicio = new javax.swing.JLabel();
        txtDescripcionServicio = new javax.swing.JTextField();
        scrServicios = new javax.swing.JScrollPane();
        tblServicios = new javax.swing.JTable();
        pnlBotonesServicio = new javax.swing.JPanel();
        btnListarServicios = new javax.swing.JButton();
        btnAgregarServicio = new javax.swing.JButton();
        btnQuitarServicio = new javax.swing.JButton();
        pnlItinerario = new javax.swing.JPanel();
        pnlCamposItinerario = new javax.swing.JPanel();
        lblCodigoItinerario = new javax.swing.JLabel();
        txtCodigoItinerario = new javax.swing.JTextField();
        lblDiaItinerario = new javax.swing.JLabel();
        txtDiaItinerario = new javax.swing.JTextField();
        lblDescripcionItinerario = new javax.swing.JLabel();
        txtDescripcionItinerario = new javax.swing.JTextField();
        scrItinerario = new javax.swing.JScrollPane();
        tblItinerario = new javax.swing.JTable();
        pnlBotonesItinerario = new javax.swing.JPanel();
        btnListarItinerario = new javax.swing.JButton();
        btnAgregarDia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(".: Mantenimiento de Paquetes Turisticos :.");

        getContentPane().setLayout(new java.awt.BorderLayout());

        pnlDatosPaquete.setLayout(new java.awt.BorderLayout());
        pnlCamposPaquete.setLayout(new java.awt.GridLayout(6, 4));
        lblCodigo.setText("Codigo:");
        pnlCamposPaquete.add(lblCodigo);

        pnlCamposPaquete.add(txtCodigo);

        lblNombre.setText("Nombre:");
        pnlCamposPaquete.add(lblNombre);

        pnlCamposPaquete.add(txtNombre);

        lblDias.setText("Duracion (dias):");
        pnlCamposPaquete.add(lblDias);

        pnlCamposPaquete.add(txtDias);

        lblNoches.setText("Duracion (noches):");
        pnlCamposPaquete.add(lblNoches);

        pnlCamposPaquete.add(txtNoches);

        lblTipo.setText("Tipo:");
        pnlCamposPaquete.add(lblTipo);

        pnlCamposPaquete.add(cboTipo);

        lblPrecio.setText("Precio por persona:");
        pnlCamposPaquete.add(lblPrecio);

        pnlCamposPaquete.add(txtPrecio);

        lblFechaSalida.setText("Fecha salida (dd/mm/aaaa):");
        pnlCamposPaquete.add(lblFechaSalida);

        pnlCamposPaquete.add(txtFechaSalida);

        lblFechaRetorno.setText("Fecha retorno (dd/mm/aaaa):");
        pnlCamposPaquete.add(lblFechaRetorno);

        pnlCamposPaquete.add(txtFechaRetorno);

        lblCupo.setText("Cupo maximo:");
        pnlCamposPaquete.add(lblCupo);

        pnlCamposPaquete.add(txtCupo);

        lblEstado.setText("Estado:");
        pnlCamposPaquete.add(lblEstado);

        pnlCamposPaquete.add(cboEstado);

        lblDestino.setText("Destino a incluir:");
        pnlCamposPaquete.add(lblDestino);

        pnlCamposPaquete.add(cboDestino);

        pnlDatosPaquete.add(pnlCamposPaquete, java.awt.BorderLayout.NORTH);

        tblPaquetes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPaquetesMouseClicked(evt);
            }
        });
        scrPaquetes.setViewportView(tblPaquetes);

        pnlDatosPaquete.add(scrPaquetes, java.awt.BorderLayout.CENTER);

        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vcsnormal.png"))); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);
        pnlBotonesPaquete.add(btnRegistrar);

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/edit.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(this::btnModificarActionPerformed);
        pnlBotonesPaquete.add(btnModificar);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/delete_remove.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);
        pnlBotonesPaquete.add(btnEliminar);

        btnAgregarDestino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/archivo.png"))); // NOI18N
        btnAgregarDestino.setText("Agregar Destino al Paquete");
        btnAgregarDestino.addActionListener(this::btnAgregarDestinoActionPerformed);
        pnlBotonesPaquete.add(btnAgregarDestino);

        btnQuitarDestino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/delete_remove.png"))); // NOI18N
        btnQuitarDestino.setText("Quitar Destino");
        btnQuitarDestino.addActionListener(this::btnQuitarDestinoActionPerformed);
        pnlBotonesPaquete.add(btnQuitarDestino);

        pnlDatosPaquete.add(pnlBotonesPaquete, java.awt.BorderLayout.SOUTH);

        tabPaquetes.addTab("Datos del Paquete", pnlDatosPaquete);

        pnlServicios.setLayout(new java.awt.BorderLayout());
        pnlCamposServicio.setLayout(new java.awt.GridLayout(3, 2));
        lblCodigoServicio.setText("Codigo del paquete:");
        pnlCamposServicio.add(lblCodigoServicio);

        pnlCamposServicio.add(txtCodigoServicio);

        lblTipoServicio.setText("Tipo de servicio:");
        pnlCamposServicio.add(lblTipoServicio);

        pnlCamposServicio.add(cboTipoServicio);

        lblDescripcionServicio.setText("Descripcion:");
        pnlCamposServicio.add(lblDescripcionServicio);

        pnlCamposServicio.add(txtDescripcionServicio);

        pnlServicios.add(pnlCamposServicio, java.awt.BorderLayout.NORTH);

        scrServicios.setViewportView(tblServicios);

        pnlServicios.add(scrServicios, java.awt.BorderLayout.CENTER);

        btnListarServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultar.png"))); // NOI18N
        btnListarServicios.setText("Listar Servicios");
        btnListarServicios.addActionListener(this::btnListarServiciosActionPerformed);
        pnlBotonesServicio.add(btnListarServicios);

        btnAgregarServicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vcsnormal.png"))); // NOI18N
        btnAgregarServicio.setText("Agregar Servicio");
        btnAgregarServicio.addActionListener(this::btnAgregarServicioActionPerformed);
        pnlBotonesServicio.add(btnAgregarServicio);

        btnQuitarServicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/delete_remove.png"))); // NOI18N
        btnQuitarServicio.setText("Quitar Servicio Seleccionado");
        btnQuitarServicio.addActionListener(this::btnQuitarServicioActionPerformed);
        pnlBotonesServicio.add(btnQuitarServicio);

        pnlServicios.add(pnlBotonesServicio, java.awt.BorderLayout.SOUTH);

        tabPaquetes.addTab("Servicios Incluidos", pnlServicios);

        pnlItinerario.setLayout(new java.awt.BorderLayout());
        pnlCamposItinerario.setLayout(new java.awt.GridLayout(3, 2));
        lblCodigoItinerario.setText("Codigo del paquete:");
        pnlCamposItinerario.add(lblCodigoItinerario);

        pnlCamposItinerario.add(txtCodigoItinerario);

        lblDiaItinerario.setText("Dia (numero):");
        pnlCamposItinerario.add(lblDiaItinerario);

        pnlCamposItinerario.add(txtDiaItinerario);

        lblDescripcionItinerario.setText("Descripcion de actividades:");
        pnlCamposItinerario.add(lblDescripcionItinerario);

        pnlCamposItinerario.add(txtDescripcionItinerario);

        pnlItinerario.add(pnlCamposItinerario, java.awt.BorderLayout.NORTH);

        scrItinerario.setViewportView(tblItinerario);

        pnlItinerario.add(scrItinerario, java.awt.BorderLayout.CENTER);

        btnListarItinerario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultar.png"))); // NOI18N
        btnListarItinerario.setText("Listar Itinerario");
        btnListarItinerario.addActionListener(this::btnListarItinerarioActionPerformed);
        pnlBotonesItinerario.add(btnListarItinerario);

        btnAgregarDia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vcsnormal.png"))); // NOI18N
        btnAgregarDia.setText("Agregar Dia");
        btnAgregarDia.addActionListener(this::btnAgregarDiaActionPerformed);
        pnlBotonesItinerario.add(btnAgregarDia);

        pnlItinerario.add(pnlBotonesItinerario, java.awt.BorderLayout.SOUTH);

        tabPaquetes.addTab("Itinerario", pnlItinerario);

        getContentPane().add(tabPaquetes, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        registrarPaquete();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        modificarPaquete();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminarPaquete();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAgregarDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDestinoActionPerformed
        agregarDestino();
    }//GEN-LAST:event_btnAgregarDestinoActionPerformed

    private void btnQuitarDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarDestinoActionPerformed
        quitarDestino();
    }//GEN-LAST:event_btnQuitarDestinoActionPerformed

    private void tblPaquetesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPaquetesMouseClicked
        int fila = tblPaquetes.getSelectedRow();
        if (fila >= 0) {
            txtCodigo.setText(modeloPaquetes.getValueAt(fila, 0).toString());
            txtNombre.setText(modeloPaquetes.getValueAt(fila, 1).toString());
            PaqueteTuristico p = agencia.getGestionPaquete().buscar(txtCodigo.getText());
            if (p != null) {
                txtDias.setText(String.valueOf(p.getDuracionDias()));
                txtNoches.setText(String.valueOf(p.getDuracionNoches()));
                cboTipo.setSelectedItem(p.getTipo());
                txtPrecio.setText(String.valueOf(p.getPrecioPorPersona()));
                txtFechaSalida.setText(p.getFechaSalida());
                txtFechaRetorno.setText(p.getFechaRetorno());
                txtCupo.setText(String.valueOf(p.getCupoMaximo()));
                cboEstado.setSelectedItem(p.getEstado());
            }
        }
    }//GEN-LAST:event_tblPaquetesMouseClicked

    private void btnListarServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarServiciosActionPerformed
        listarServicios();
    }//GEN-LAST:event_btnListarServiciosActionPerformed

    private void btnAgregarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarServicioActionPerformed
        agregarServicio();
    }//GEN-LAST:event_btnAgregarServicioActionPerformed

    private void btnQuitarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarServicioActionPerformed
        quitarServicio();
    }//GEN-LAST:event_btnQuitarServicioActionPerformed

    private void btnListarItinerarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarItinerarioActionPerformed
        listarItinerario();
    }//GEN-LAST:event_btnListarItinerarioActionPerformed

    private void btnAgregarDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDiaActionPerformed
        agregarDia();
    }//GEN-LAST:event_btnAgregarDiaActionPerformed

    private void cargarDestinos() {
        cboDestino.removeAllItems();
        DestinoTuristico[] destinos = agencia.getGestionDestino().obtenerDestinos();
        int total = agencia.getGestionDestino().obtenerTotalDestinos();
        for (int i = 0; i < total; i++) {
            cboDestino.addItem(destinos[i].getNombre());
        }
    }

    private PaqueteTuristico construirPaquete() {
        try {
            return new PaqueteTuristico(txtCodigo.getText().trim(), txtNombre.getText().trim(),
                    Integer.parseInt(txtDias.getText().trim()),
                    Integer.parseInt(txtNoches.getText().trim()),
                    cboTipo.getSelectedItem().toString(),
                    Double.parseDouble(txtPrecio.getText().trim()),
                    txtFechaSalida.getText().trim(), txtFechaRetorno.getText().trim(),
                    Integer.parseInt(txtCupo.getText().trim()),
                    cboEstado.getSelectedItem().toString());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Verifique los valores numericos (dias, noches, precio, cupo)");
            return null;
        }
    }

    private void registrarPaquete() {
        if (txtCodigo.getText().trim().equals("") || txtNombre.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese codigo y nombre del paquete");
            return;
        }
        PaqueteTuristico paquete = construirPaquete();
        if (paquete == null) {
            return;
        }
        if (agencia.getGestionPaquete().registrar(paquete)) {
            JOptionPane.showMessageDialog(this, "Paquete registrado. Ahora agregue destinos, servicios e itinerario.");
            listarPaquetes();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo registrar (codigo duplicado)");
        }
    }

    private void modificarPaquete() {
        PaqueteTuristico paquete = construirPaquete();
        if (paquete == null) {
            return;
        }
        if (agencia.getGestionPaquete().actualizar(paquete)) {
            JOptionPane.showMessageDialog(this, "Paquete modificado correctamente");
            listarPaquetes();
        } else {
            JOptionPane.showMessageDialog(this, "No se encontro el paquete");
        }
    }

    private void eliminarPaquete() {
        if (agencia.getGestionPaquete().eliminar(txtCodigo.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Paquete eliminado");
            listarPaquetes();
        } else {
            JOptionPane.showMessageDialog(this, "No se encontro el paquete");
        }
    }

    private void agregarDestino() {
        PaqueteTuristico paquete = agencia.getGestionPaquete().buscar(txtCodigo.getText().trim());
        if (paquete == null) {
            JOptionPane.showMessageDialog(this, "Primero seleccione o registre el paquete");
            return;
        }
        if (cboDestino.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "No hay destinos registrados");
            return;
        }
        DestinoTuristico destino = agencia.getGestionDestino().buscar(cboDestino.getSelectedItem().toString());
        if (paquete.agregarDestino(destino)) {
            JOptionPane.showMessageDialog(this, "Destino agregado al paquete");
            listarPaquetes();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo agregar (el destino ya esta en el paquete o no hay espacio)");
        }
    }

    private void quitarDestino() {
        PaqueteTuristico paquete = agencia.getGestionPaquete().buscar(txtCodigo.getText().trim());
        if (paquete == null) {
            JOptionPane.showMessageDialog(this, "Primero seleccione el paquete en la tabla");
            return;
        }
        if (cboDestino.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Seleccione en el combo el destino a quitar");
            return;
        }
        if (paquete.eliminarDestino(cboDestino.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(this, "Destino quitado del paquete");
            listarPaquetes();
        } else {
            JOptionPane.showMessageDialog(this, "Ese destino no esta incluido en el paquete");
        }
    }

    private void listarPaquetes() {
        modeloPaquetes.setRowCount(0);
        PaqueteTuristico[] paquetes = agencia.getGestionPaquete().obtenerPaquetes();
        int total = agencia.getGestionPaquete().obtenerTotalPaquetes();
        for (int i = 0; i < total; i++) {
            PaqueteTuristico p = paquetes[i];
            modeloPaquetes.addRow(new Object[]{p.getCodigo(), p.getNombre(), p.obtenerNombresDestinos(),
                p.getDuracionDias() + "D/" + p.getDuracionNoches() + "N", p.getTipo(),
                p.getPrecioPorPersona(), p.getFechaSalida(), p.getFechaRetorno(),
                p.getCupoDisponible() + "/" + p.getCupoMaximo(), p.getEstado()});
        }
    }

    private void listarServicios() {
        PaqueteTuristico paquete = agencia.getGestionPaquete().buscar(txtCodigoServicio.getText().trim());
        if (paquete == null) {
            JOptionPane.showMessageDialog(this, "No se encontro el paquete");
            return;
        }
        modeloServicios.setRowCount(0);
        ServicioIncluido[] servicios = paquete.obtenerServicios();
        for (int i = 0; i < paquete.obtenerTotalServicios(); i++) {
            modeloServicios.addRow(new Object[]{servicios[i].getTipo(), servicios[i].getDescripcion()});
        }
    }

    private void agregarServicio() {
        PaqueteTuristico paquete = agencia.getGestionPaquete().buscar(txtCodigoServicio.getText().trim());
        if (paquete == null) {
            JOptionPane.showMessageDialog(this, "No se encontro el paquete");
            return;
        }
        if (txtDescripcionServicio.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese la descripcion del servicio");
            return;
        }
        paquete.agregarServicio(new ServicioIncluido(cboTipoServicio.getSelectedItem().toString(),
                txtDescripcionServicio.getText().trim()));
        txtDescripcionServicio.setText("");
        listarServicios();
    }

    private void quitarServicio() {
        PaqueteTuristico paquete = agencia.getGestionPaquete().buscar(txtCodigoServicio.getText().trim());
        int fila = tblServicios.getSelectedRow();
        if (paquete == null || fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un servicio de la tabla");
            return;
        }
        paquete.eliminarServicio(fila);
        listarServicios();
    }

    private void listarItinerario() {
        PaqueteTuristico paquete = agencia.getGestionPaquete().buscar(txtCodigoItinerario.getText().trim());
        if (paquete == null) {
            JOptionPane.showMessageDialog(this, "No se encontro el paquete");
            return;
        }
        modeloItinerario.setRowCount(0);
        ItinerarioDia[] itinerario = paquete.obtenerItinerario();
        for (int i = 0; i < paquete.obtenerTotalDiasItinerario(); i++) {
            modeloItinerario.addRow(new Object[]{itinerario[i].getDia(), itinerario[i].getDescripcion()});
        }
    }

    private void agregarDia() {
        PaqueteTuristico paquete = agencia.getGestionPaquete().buscar(txtCodigoItinerario.getText().trim());
        if (paquete == null) {
            JOptionPane.showMessageDialog(this, "No se encontro el paquete");
            return;
        }
        try {
            int dia = Integer.parseInt(txtDiaItinerario.getText().trim());
            if (txtDescripcionItinerario.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Ingrese la descripcion de actividades");
                return;
            }
            paquete.agregarDiaItinerario(new ItinerarioDia(dia, txtDescripcionItinerario.getText().trim()));
            txtDiaItinerario.setText("");
            txtDescripcionItinerario.setText("");
            listarItinerario();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El dia debe ser un numero");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabPaquetes;
    private javax.swing.JPanel pnlDatosPaquete;
    private javax.swing.JPanel pnlCamposPaquete;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JLabel lblDias;
    private javax.swing.JTextField txtDias;
    private javax.swing.JLabel lblNoches;
    private javax.swing.JTextField txtNoches;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JComboBox<String> cboTipo;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JLabel lblFechaSalida;
    private javax.swing.JTextField txtFechaSalida;
    private javax.swing.JLabel lblFechaRetorno;
    private javax.swing.JTextField txtFechaRetorno;
    private javax.swing.JLabel lblCupo;
    private javax.swing.JTextField txtCupo;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JComboBox<String> cboEstado;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JComboBox<String> cboDestino;
    private javax.swing.JScrollPane scrPaquetes;
    private javax.swing.JTable tblPaquetes;
    private javax.swing.JPanel pnlBotonesPaquete;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnAgregarDestino;
    private javax.swing.JButton btnQuitarDestino;
    private javax.swing.JPanel pnlServicios;
    private javax.swing.JPanel pnlCamposServicio;
    private javax.swing.JLabel lblCodigoServicio;
    private javax.swing.JTextField txtCodigoServicio;
    private javax.swing.JLabel lblTipoServicio;
    private javax.swing.JComboBox<String> cboTipoServicio;
    private javax.swing.JLabel lblDescripcionServicio;
    private javax.swing.JTextField txtDescripcionServicio;
    private javax.swing.JScrollPane scrServicios;
    private javax.swing.JTable tblServicios;
    private javax.swing.JPanel pnlBotonesServicio;
    private javax.swing.JButton btnListarServicios;
    private javax.swing.JButton btnAgregarServicio;
    private javax.swing.JButton btnQuitarServicio;
    private javax.swing.JPanel pnlItinerario;
    private javax.swing.JPanel pnlCamposItinerario;
    private javax.swing.JLabel lblCodigoItinerario;
    private javax.swing.JTextField txtCodigoItinerario;
    private javax.swing.JLabel lblDiaItinerario;
    private javax.swing.JTextField txtDiaItinerario;
    private javax.swing.JLabel lblDescripcionItinerario;
    private javax.swing.JTextField txtDescripcionItinerario;
    private javax.swing.JScrollPane scrItinerario;
    private javax.swing.JTable tblItinerario;
    private javax.swing.JPanel pnlBotonesItinerario;
    private javax.swing.JButton btnListarItinerario;
    private javax.swing.JButton btnAgregarDia;
    // End of variables declaration//GEN-END:variables
}
