/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import clases.Promocion;
import clases.PromocionMontoFijo;
import clases.PromocionPorcentaje;
import clases.PromocionTemporada;
import gestion.Agencia;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bloque7
 */
public class frmPromociones extends javax.swing.JFrame {

    private Agencia agencia;
    private DefaultTableModel modelo;

    /**
     * Creates new form frmPromociones
     */
    public frmPromociones(Agencia agencia) {
        this.agencia = agencia;
        initComponents();
        cboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[]{"Porcentaje", "Monto Fijo", "Temporada"}));
        modelo = new DefaultTableModel(new String[]{"Codigo", "Descripcion", "Paquete",
            "Tipo", "Inicio", "Fin"}, 0);
        tblPromociones.setModel(modelo);
        setSize(860, 520);
        setLocationRelativeTo(null);
        listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDatos = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        lblCodigoPaquete = new javax.swing.JLabel();
        txtCodigoPaquete = new javax.swing.JTextField();
        lblFechaInicio = new javax.swing.JLabel();
        txtFechaInicio = new javax.swing.JTextField();
        lblFechaFin = new javax.swing.JLabel();
        txtFechaFin = new javax.swing.JTextField();
        lblTipo = new javax.swing.JLabel();
        cboTipo = new javax.swing.JComboBox<>();
        lblValor = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        lblTemporada = new javax.swing.JLabel();
        txtTemporada = new javax.swing.JTextField();
        scrTabla = new javax.swing.JScrollPane();
        tblPromociones = new javax.swing.JTable();
        pnlBotones = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(".: Promociones y Descuentos :.");

        getContentPane().setLayout(new java.awt.BorderLayout());

        pnlDatos.setLayout(new java.awt.GridLayout(8, 2));
        lblCodigo.setText("Codigo:");
        pnlDatos.add(lblCodigo);

        pnlDatos.add(txtCodigo);

        lblDescripcion.setText("Descripcion:");
        pnlDatos.add(lblDescripcion);

        pnlDatos.add(txtDescripcion);

        lblCodigoPaquete.setText("Codigo del paquete:");
        pnlDatos.add(lblCodigoPaquete);

        pnlDatos.add(txtCodigoPaquete);

        lblFechaInicio.setText("Vigencia desde (dd/mm/aaaa):");
        pnlDatos.add(lblFechaInicio);

        pnlDatos.add(txtFechaInicio);

        lblFechaFin.setText("Vigencia hasta (dd/mm/aaaa):");
        pnlDatos.add(lblFechaFin);

        pnlDatos.add(txtFechaFin);

        lblTipo.setText("Tipo de promocion:");
        pnlDatos.add(lblTipo);

        pnlDatos.add(cboTipo);

        lblValor.setText("Valor (% o monto S/):");
        pnlDatos.add(lblValor);

        pnlDatos.add(txtValor);

        lblTemporada.setText("Temporada (solo tipo Temporada):");
        pnlDatos.add(lblTemporada);

        pnlDatos.add(txtTemporada);

        getContentPane().add(pnlDatos, java.awt.BorderLayout.NORTH);

        scrTabla.setViewportView(tblPromociones);

        getContentPane().add(scrTabla, java.awt.BorderLayout.CENTER);

        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vcsnormal.png"))); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);
        pnlBotones.add(btnRegistrar);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/delete_remove.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);
        pnlBotones.add(btnEliminar);

        getContentPane().add(pnlBotones, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        registrar();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void registrar() {
        if (txtCodigo.getText().trim().equals("") || txtCodigoPaquete.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese el codigo de la promocion y del paquete");
            return;
        }
        if (agencia.getGestionPaquete().buscar(txtCodigoPaquete.getText().trim()) == null) {
            JOptionPane.showMessageDialog(this, "El paquete indicado no existe");
            return;
        }
        double valor;
        try {
            valor = Double.parseDouble(txtValor.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El valor debe ser numerico");
            return;
        }

        String tipo = cboTipo.getSelectedItem().toString();
        Promocion promocion;
        if (tipo.equals("Porcentaje")) {
            promocion = new PromocionPorcentaje(txtCodigo.getText().trim(), txtDescripcion.getText().trim(),
                    txtCodigoPaquete.getText().trim(), txtFechaInicio.getText().trim(),
                    txtFechaFin.getText().trim(), valor);
        } else if (tipo.equals("Monto Fijo")) {
            promocion = new PromocionMontoFijo(txtCodigo.getText().trim(), txtDescripcion.getText().trim(),
                    txtCodigoPaquete.getText().trim(), txtFechaInicio.getText().trim(),
                    txtFechaFin.getText().trim(), valor);
        } else {
            promocion = new PromocionTemporada(txtCodigo.getText().trim(), txtDescripcion.getText().trim(),
                    txtCodigoPaquete.getText().trim(), txtFechaInicio.getText().trim(),
                    txtFechaFin.getText().trim(), txtTemporada.getText().trim(), valor);
        }

        if (agencia.getGestionPromocion().registrar(promocion)) {
            JOptionPane.showMessageDialog(this, "Promocion registrada correctamente");
            listar();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo registrar (codigo duplicado)");
        }
    }

    private void eliminar() {
        int fila = tblPromociones.getSelectedRow();
        String codigo = fila >= 0 ? modelo.getValueAt(fila, 0).toString() : txtCodigo.getText().trim();
        if (agencia.getGestionPromocion().eliminar(codigo)) {
            JOptionPane.showMessageDialog(this, "Promocion eliminada");
            listar();
        } else {
            JOptionPane.showMessageDialog(this, "No se encontro la promocion");
        }
    }

    private void listar() {
        modelo.setRowCount(0);
        Promocion[] promociones = agencia.getGestionPromocion().obtenerPromociones();
        int total = agencia.getGestionPromocion().obtenerTotalPromociones();
        for (int i = 0; i < total; i++) {
            Promocion p = promociones[i];
            modelo.addRow(new Object[]{p.getCodigo(), p.getDescripcion(), p.getCodigoPaquete(),
                p.obtenerTipo(), p.getFechaInicio(), p.getFechaFin()});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JLabel lblCodigoPaquete;
    private javax.swing.JTextField txtCodigoPaquete;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JTextField txtFechaInicio;
    private javax.swing.JLabel lblFechaFin;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JComboBox<String> cboTipo;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTextField txtValor;
    private javax.swing.JLabel lblTemporada;
    private javax.swing.JTextField txtTemporada;
    private javax.swing.JScrollPane scrTabla;
    private javax.swing.JTable tblPromociones;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnEliminar;
    // End of variables declaration//GEN-END:variables
}
