/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import clases.Empleado;
import gestion.Agencia;

/**
 *
 * @author Bloque7
 */
public class frmPrincipal extends javax.swing.JFrame {

    private Agencia agencia;
    private Empleado empleado;

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal(Agencia agencia, Empleado empleado) {
        this.agencia = agencia;
        this.empleado = empleado;
        initComponents();
        setTitle(".: ULIMA TRAVEL - " + empleado.obtenerRol() + ": "
                + empleado.obtenerNombreCompleto() + " :.");
        setSize(1100, 700);
        setLocationRelativeTo(null);
        cargarPermisos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        mnMantenimiento = new javax.swing.JMenu();
        mnitmEmpleados = new javax.swing.JMenuItem();
        mnitmDestinos = new javax.swing.JMenuItem();
        mnitmPaquetes = new javax.swing.JMenuItem();
        mnitmPromociones = new javax.swing.JMenuItem();
        mnVentas = new javax.swing.JMenu();
        mnitmClientes = new javax.swing.JMenuItem();
        mnitmReservas = new javax.swing.JMenuItem();
        mnitmPagos = new javax.swing.JMenuItem();
        mnConsultas = new javax.swing.JMenu();
        mnitmItinerarios = new javax.swing.JMenuItem();
        mnReportes = new javax.swing.JMenu();
        mnitmReportes = new javax.swing.JMenuItem();
        mnSalir = new javax.swing.JMenu();
        mnitmCerrarSesion = new javax.swing.JMenuItem();
        mnitmSalirSistema = new javax.swing.JMenuItem();
        pnlFondo = new javax.swing.JPanel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(".: ULIMA TRAVEL - Agencia de Viajes :.");

        mnMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mantenimiento.png"))); // NOI18N
        mnMantenimiento.setText("Mantenimiento");

        mnitmEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/archivo.png"))); // NOI18N
        mnitmEmpleados.setText("Empleados");
        mnitmEmpleados.addActionListener(this::mnitmEmpleadosActionPerformed);
        mnMantenimiento.add(mnitmEmpleados);

        mnitmDestinos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/archivo.png"))); // NOI18N
        mnitmDestinos.setText("Destinos Turisticos");
        mnitmDestinos.addActionListener(this::mnitmDestinosActionPerformed);
        mnMantenimiento.add(mnitmDestinos);

        mnitmPaquetes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/archivo.png"))); // NOI18N
        mnitmPaquetes.setText("Paquetes Turisticos");
        mnitmPaquetes.addActionListener(this::mnitmPaquetesActionPerformed);
        mnMantenimiento.add(mnitmPaquetes);

        mnitmPromociones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/archivo.png"))); // NOI18N
        mnitmPromociones.setText("Promociones y Descuentos");
        mnitmPromociones.addActionListener(this::mnitmPromocionesActionPerformed);
        mnMantenimiento.add(mnitmPromociones);

        menuBar.add(mnMantenimiento);

        mnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/book.png"))); // NOI18N
        mnVentas.setText("Ventas");

        mnitmClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/book.png"))); // NOI18N
        mnitmClientes.setText("Clientes");
        mnitmClientes.addActionListener(this::mnitmClientesActionPerformed);
        mnVentas.add(mnitmClientes);

        mnitmReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vcsnormal.png"))); // NOI18N
        mnitmReservas.setText("Reservas");
        mnitmReservas.addActionListener(this::mnitmReservasActionPerformed);
        mnVentas.add(mnitmReservas);

        mnitmPagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vcsnormal.png"))); // NOI18N
        mnitmPagos.setText("Pagos");
        mnitmPagos.addActionListener(this::mnitmPagosActionPerformed);
        mnVentas.add(mnitmPagos);

        menuBar.add(mnVentas);

        mnConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultar.png"))); // NOI18N
        mnConsultas.setText("Consultas");

        mnitmItinerarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultar.png"))); // NOI18N
        mnitmItinerarios.setText("Itinerarios y Cupos");
        mnitmItinerarios.addActionListener(this::mnitmItinerariosActionPerformed);
        mnConsultas.add(mnitmItinerarios);

        menuBar.add(mnConsultas);

        mnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporte.png"))); // NOI18N
        mnReportes.setText("Reportes");

        mnitmReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporte.png"))); // NOI18N
        mnitmReportes.setText("Generar Reportes");
        mnitmReportes.addActionListener(this::mnitmReportesActionPerformed);
        mnReportes.add(mnitmReportes);

        menuBar.add(mnReportes);

        mnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        mnSalir.setText("Salir");

        mnitmCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/update_rotation.png"))); // NOI18N
        mnitmCerrarSesion.setText("Cerrar Sesion");
        mnitmCerrarSesion.addActionListener(this::mnitmCerrarSesionActionPerformed);
        mnSalir.add(mnitmCerrarSesion);

        mnitmSalirSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        mnitmSalirSistema.setText("Salir del Sistema");
        mnitmSalirSistema.addActionListener(this::mnitmSalirSistemaActionPerformed);
        mnSalir.add(mnitmSalirSistema);

        menuBar.add(mnSalir);

        getContentPane().setLayout(new java.awt.BorderLayout());

        pnlFondo.setBackground(new java.awt.Color(18, 65, 102));
        pnlFondo.setLayout(new java.awt.BorderLayout());
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoAgencia.jpg"))); // NOI18N
        lblFondo.setHorizontalAlignment(0);
        pnlFondo.add(lblFondo, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlFondo, java.awt.BorderLayout.CENTER);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnitmEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitmEmpleadosActionPerformed
        abrir(new frmEmpleados(agencia));
    }//GEN-LAST:event_mnitmEmpleadosActionPerformed

    private void mnitmDestinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitmDestinosActionPerformed
        abrir(new frmDestinos(agencia));
    }//GEN-LAST:event_mnitmDestinosActionPerformed

    private void mnitmPaquetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitmPaquetesActionPerformed
        abrir(new frmPaquetes(agencia));
    }//GEN-LAST:event_mnitmPaquetesActionPerformed

    private void mnitmPromocionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitmPromocionesActionPerformed
        abrir(new frmPromociones(agencia));
    }//GEN-LAST:event_mnitmPromocionesActionPerformed

    private void mnitmClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitmClientesActionPerformed
        abrir(new frmClientes(agencia));
    }//GEN-LAST:event_mnitmClientesActionPerformed

    private void mnitmReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitmReservasActionPerformed
        abrir(new frmReservas(agencia, empleado));
    }//GEN-LAST:event_mnitmReservasActionPerformed

    private void mnitmPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitmPagosActionPerformed
        abrir(new frmPagos(agencia));
    }//GEN-LAST:event_mnitmPagosActionPerformed

    private void mnitmItinerariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitmItinerariosActionPerformed
        abrir(new frmItinerarios(agencia));
    }//GEN-LAST:event_mnitmItinerariosActionPerformed

    private void mnitmReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitmReportesActionPerformed
        abrir(new frmReportes(agencia));
    }//GEN-LAST:event_mnitmReportesActionPerformed

    private void mnitmCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitmCerrarSesionActionPerformed
        new frmLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnitmCerrarSesionActionPerformed

    private void mnitmSalirSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitmSalirSistemaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnitmSalirSistemaActionPerformed

    private void cargarPermisos() {
        String rol = empleado.obtenerRol();
        if (rol.equals("Administrador")) {
            mnMantenimiento.setVisible(true);
            mnVentas.setVisible(false);
            mnConsultas.setVisible(true);
            mnReportes.setVisible(true);
        } else if (rol.equals("Asesor de Viaje")) {
            mnMantenimiento.setVisible(false);
            mnVentas.setVisible(true);
            mnConsultas.setVisible(true);
            mnReportes.setVisible(true);
        } else if (rol.equals("Operador")) {
            mnMantenimiento.setVisible(false);
            mnVentas.setVisible(false);
            mnConsultas.setVisible(true);
            mnReportes.setVisible(false);
        }
        mnSalir.setVisible(true);
    }

    private void abrir(javax.swing.JFrame ventana) {
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnMantenimiento;
    private javax.swing.JMenuItem mnitmEmpleados;
    private javax.swing.JMenuItem mnitmDestinos;
    private javax.swing.JMenuItem mnitmPaquetes;
    private javax.swing.JMenuItem mnitmPromociones;
    private javax.swing.JMenu mnVentas;
    private javax.swing.JMenuItem mnitmClientes;
    private javax.swing.JMenuItem mnitmReservas;
    private javax.swing.JMenuItem mnitmPagos;
    private javax.swing.JMenu mnConsultas;
    private javax.swing.JMenuItem mnitmItinerarios;
    private javax.swing.JMenu mnReportes;
    private javax.swing.JMenuItem mnitmReportes;
    private javax.swing.JMenu mnSalir;
    private javax.swing.JMenuItem mnitmCerrarSesion;
    private javax.swing.JMenuItem mnitmSalirSistema;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JLabel lblFondo;
    // End of variables declaration//GEN-END:variables
}
