/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import gestion.Agencia;
import javax.swing.JOptionPane;

/**
 *
 * @author Bloque7
 */
public class frmReportes extends javax.swing.JFrame {

    private Agencia agencia;

    /**
     * Creates new form frmReportes
     */
    public frmReportes(Agencia agencia) {
        this.agencia = agencia;
        initComponents();
        txtReporte.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 13));
        setSize(820, 560);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFiltros = new javax.swing.JPanel();
        lblCodigoPaquete = new javax.swing.JLabel();
        txtCodigoPaquete = new javax.swing.JTextField();
        lblFechaInicio = new javax.swing.JLabel();
        txtFechaInicio = new javax.swing.JTextField();
        lblFechaFin = new javax.swing.JLabel();
        txtFechaFin = new javax.swing.JTextField();
        scrReporte = new javax.swing.JScrollPane();
        txtReporte = new javax.swing.JTextArea();
        pnlBotones = new javax.swing.JPanel();
        btnReporte1 = new javax.swing.JButton();
        btnReporte2 = new javax.swing.JButton();
        btnReporte3 = new javax.swing.JButton();
        btnReporte4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(".: Reportes del Sistema :.");

        getContentPane().setLayout(new java.awt.BorderLayout());

        pnlFiltros.setLayout(new java.awt.GridLayout(3, 2));
        lblCodigoPaquete.setText("Codigo de paquete (reporte 1):");
        pnlFiltros.add(lblCodigoPaquete);

        pnlFiltros.add(txtCodigoPaquete);

        lblFechaInicio.setText("Fecha inicio (dd/mm/aaaa):");
        pnlFiltros.add(lblFechaInicio);

        pnlFiltros.add(txtFechaInicio);

        lblFechaFin.setText("Fecha fin (dd/mm/aaaa):");
        pnlFiltros.add(lblFechaFin);

        pnlFiltros.add(txtFechaFin);

        getContentPane().add(pnlFiltros, java.awt.BorderLayout.NORTH);

        txtReporte.setEditable(false);
        scrReporte.setViewportView(txtReporte);

        getContentPane().add(scrReporte, java.awt.BorderLayout.CENTER);

        pnlBotones.setLayout(new java.awt.GridLayout(2, 2));
        btnReporte1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporte.png"))); // NOI18N
        btnReporte1.setText("1. Reservas por Paquete y Fechas");
        btnReporte1.addActionListener(this::btnReporte1ActionPerformed);
        pnlBotones.add(btnReporte1);

        btnReporte2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporte.png"))); // NOI18N
        btnReporte2.setText("2. Destinos mas Solicitados");
        btnReporte2.addActionListener(this::btnReporte2ActionPerformed);
        pnlBotones.add(btnReporte2);

        btnReporte3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporte.png"))); // NOI18N
        btnReporte3.setText("3. Ingresos por Asesor");
        btnReporte3.addActionListener(this::btnReporte3ActionPerformed);
        pnlBotones.add(btnReporte3);

        btnReporte4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporte.png"))); // NOI18N
        btnReporte4.setText("4. Clientes con Reservas Pendientes de Pago");
        btnReporte4.addActionListener(this::btnReporte4ActionPerformed);
        pnlBotones.add(btnReporte4);

        getContentPane().add(pnlBotones, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReporte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporte1ActionPerformed
        generarReporte1();
    }//GEN-LAST:event_btnReporte1ActionPerformed

    private void btnReporte2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporte2ActionPerformed
        txtReporte.setText(agencia.getGestionReserva().reporteDestinosMasSolicitados());
    }//GEN-LAST:event_btnReporte2ActionPerformed

    private void btnReporte3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporte3ActionPerformed
        txtReporte.setText(agencia.getGestionReserva().reporteIngresosPorAsesor());
    }//GEN-LAST:event_btnReporte3ActionPerformed

    private void btnReporte4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporte4ActionPerformed
        txtReporte.setText(agencia.getGestionReserva().reporteClientesConReservas());
    }//GEN-LAST:event_btnReporte4ActionPerformed

    private void generarReporte1() {
        if (txtCodigoPaquete.getText().trim().equals("")
                || txtFechaInicio.getText().trim().equals("")
                || txtFechaFin.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Complete el codigo del paquete y el rango de fechas");
            return;
        }
        try {
            txtReporte.setText(agencia.getGestionReserva().reporteReservasPorPaquete(
                    txtCodigoPaquete.getText().trim(), txtFechaInicio.getText().trim(),
                    txtFechaFin.getText().trim()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Formato de fecha incorrecto. Use dd/mm/aaaa");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlFiltros;
    private javax.swing.JLabel lblCodigoPaquete;
    private javax.swing.JTextField txtCodigoPaquete;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JTextField txtFechaInicio;
    private javax.swing.JLabel lblFechaFin;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JScrollPane scrReporte;
    private javax.swing.JTextArea txtReporte;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JButton btnReporte1;
    private javax.swing.JButton btnReporte2;
    private javax.swing.JButton btnReporte3;
    private javax.swing.JButton btnReporte4;
    // End of variables declaration//GEN-END:variables
}
