/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import clases.AsesorViaje;
import clases.Cliente;
import clases.Empleado;
import clases.PaqueteTuristico;
import clases.Reserva;
import gestion.Agencia;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Bloque7
 */
public class frmReservas extends javax.swing.JFrame {

    private Agencia agencia;
    private Empleado empleado;
    private DefaultListModel<String> modeloLista;
    private Cliente[] clientesSeleccionados;
    private int totalSeleccionados;

    /**
     * Creates new form frmReservas
     */
    public frmReservas(Agencia agencia, Empleado empleado) {
        this.agencia = agencia;
        this.empleado = empleado;
        clientesSeleccionados = new Cliente[20];
        totalSeleccionados = 0;
        initComponents();
        lblInformacion.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        modeloLista = new DefaultListModel<>();
        lstClientes.setModel(modeloLista);
        cargarPaquetes();
        setSize(760, 540);
        setLocationRelativeTo(null);
        mostrarInformacionPaquete();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDatos = new javax.swing.JPanel();
        lblPaquete = new javax.swing.JLabel();
        cboPaquete = new javax.swing.JComboBox<>();
        lblDocumento = new javax.swing.JLabel();
        txtDocumentoCliente = new javax.swing.JTextField();
        lblAdultos = new javax.swing.JLabel();
        txtAdultos = new javax.swing.JTextField();
        lblMenores = new javax.swing.JLabel();
        txtMenores = new javax.swing.JTextField();
        lblPuntos = new javax.swing.JLabel();
        txtPuntosCanje = new javax.swing.JTextField();
        lblInfo = new javax.swing.JLabel();
        lblInformacion = new javax.swing.JLabel();
        pnlCentro = new javax.swing.JPanel();
        lblGrupo = new javax.swing.JLabel();
        scrLista = new javax.swing.JScrollPane();
        lstClientes = new javax.swing.JList<>();
        pnlBotones = new javax.swing.JPanel();
        btnAgregarCliente = new javax.swing.JButton();
        btnCrearReserva = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(".: Reserva de Paquete Turistico :.");

        getContentPane().setLayout(new java.awt.BorderLayout());

        pnlDatos.setLayout(new java.awt.GridLayout(6, 2));
        lblPaquete.setText("Paquete turistico:");
        pnlDatos.add(lblPaquete);

        cboPaquete.addActionListener(this::cboPaqueteActionPerformed);
        pnlDatos.add(cboPaquete);

        lblDocumento.setText("Documento del cliente:");
        pnlDatos.add(lblDocumento);

        pnlDatos.add(txtDocumentoCliente);

        lblAdultos.setText("Numero de adultos:");
        pnlDatos.add(lblAdultos);

        pnlDatos.add(txtAdultos);

        lblMenores.setText("Numero de menores:");
        pnlDatos.add(lblMenores);

        pnlDatos.add(txtMenores);

        lblPuntos.setText("Puntos a canjear (titular):");
        pnlDatos.add(lblPuntos);

        txtPuntosCanje.setText("0");
        pnlDatos.add(txtPuntosCanje);

        lblInfo.setText("Informacion del paquete:");
        pnlDatos.add(lblInfo);

        lblInformacion.setText(" ");
        pnlDatos.add(lblInformacion);

        getContentPane().add(pnlDatos, java.awt.BorderLayout.NORTH);

        pnlCentro.setLayout(new java.awt.BorderLayout());
        lblGrupo.setText("Clientes del grupo (el primero es el titular):");
        pnlCentro.add(lblGrupo, java.awt.BorderLayout.NORTH);

        scrLista.setViewportView(lstClientes);

        pnlCentro.add(scrLista, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlCentro, java.awt.BorderLayout.CENTER);

        btnAgregarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/book.png"))); // NOI18N
        btnAgregarCliente.setText("Agregar Cliente al Grupo");
        btnAgregarCliente.addActionListener(this::btnAgregarClienteActionPerformed);
        pnlBotones.add(btnAgregarCliente);

        btnCrearReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vcsnormal.png"))); // NOI18N
        btnCrearReserva.setText("Crear Reserva");
        btnCrearReserva.addActionListener(this::btnCrearReservaActionPerformed);
        pnlBotones.add(btnCrearReserva);

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/update_rotation.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);
        pnlBotones.add(btnLimpiar);

        getContentPane().add(pnlBotones, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPaqueteActionPerformed
        mostrarInformacionPaquete();
    }//GEN-LAST:event_cboPaqueteActionPerformed

    private void btnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClienteActionPerformed
        agregarCliente();
    }//GEN-LAST:event_btnAgregarClienteActionPerformed

    private void btnCrearReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearReservaActionPerformed
        crearReserva();
    }//GEN-LAST:event_btnCrearReservaActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void cargarPaquetes() {
        cboPaquete.removeAllItems();
        PaqueteTuristico[] paquetes = agencia.getGestionPaquete().obtenerPaquetes();
        int total = agencia.getGestionPaquete().obtenerTotalPaquetes();
        for (int i = 0; i < total; i++) {
            cboPaquete.addItem(paquetes[i].getCodigo() + " - " + paquetes[i].getNombre());
        }
    }

    private PaqueteTuristico obtenerPaqueteSeleccionado() {
        if (cboPaquete.getSelectedItem() == null) {
            return null;
        }
        String codigo = cboPaquete.getSelectedItem().toString().split(" - ")[0];
        return agencia.getGestionPaquete().buscar(codigo);
    }

    private void mostrarInformacionPaquete() {
        PaqueteTuristico paquete = obtenerPaqueteSeleccionado();
        if (paquete != null && lblInformacion != null) {
            lblInformacion.setText("S/ " + paquete.getPrecioPorPersona() + " por persona | Cupos: "
                    + paquete.getCupoDisponible() + " | Estado: " + paquete.getEstado());
        }
    }

    private void agregarCliente() {
        if (totalSeleccionados == clientesSeleccionados.length) {
            JOptionPane.showMessageDialog(this, "Ya no se pueden agregar mas clientes");
            return;
        }
        Cliente cliente = agencia.getGestionCliente().buscar(txtDocumentoCliente.getText().trim());
        if (cliente == null) {
            JOptionPane.showMessageDialog(this, "Cliente no encontrado. Registrelo primero en Ventas > Clientes");
            return;
        }
        for (int i = 0; i < totalSeleccionados; i++) {
            if (clientesSeleccionados[i].getDni().equalsIgnoreCase(cliente.getDni())) {
                JOptionPane.showMessageDialog(this, "El cliente ya esta en el grupo");
                return;
            }
        }
        clientesSeleccionados[totalSeleccionados] = cliente;
        totalSeleccionados++;
        modeloLista.addElement(cliente.getDni() + " - " + cliente.obtenerNombreCompleto()
                + " (Puntos: " + cliente.obtenerPuntos() + ")");
        txtDocumentoCliente.setText("");
    }

    private void crearReserva() {
        PaqueteTuristico paquete = obtenerPaqueteSeleccionado();
        if (paquete == null) {
            JOptionPane.showMessageDialog(this, "Seleccione un paquete");
            return;
        }
        if (totalSeleccionados == 0) {
            JOptionPane.showMessageDialog(this, "Agregue al menos un cliente al grupo");
            return;
        }
        int adultos;
        int menores;
        int puntos;
        try {
            adultos = Integer.parseInt(txtAdultos.getText().trim());
            menores = Integer.parseInt(txtMenores.getText().trim());
            puntos = Integer.parseInt(txtPuntosCanje.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Adultos, menores y puntos deben ser numeros");
            return;
        }
        if (adultos + menores <= 0) {
            JOptionPane.showMessageDialog(this, "Debe haber al menos un pasajero");
            return;
        }
        if (adultos + menores > paquete.getCupoDisponible()) {
            JOptionPane.showMessageDialog(this, "No hay cupos suficientes. Cupos disponibles: "
                    + paquete.getCupoDisponible());
            return;
        }

        AsesorViaje asesor;
        if (empleado instanceof AsesorViaje) {
            asesor = (AsesorViaje) empleado;
        } else {
            JOptionPane.showMessageDialog(this, "Solo un Asesor de Viaje puede crear reservas");
            return;
        }

        String fechaHoy = LocalDate.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        Reserva reserva = agencia.getGestionReserva().crearReserva(fechaHoy, paquete,
                clientesSeleccionados, totalSeleccionados, adultos, menores, asesor);

        if (reserva == null) {
            JOptionPane.showMessageDialog(this, "No se pudo crear la reserva (verifique cupos y estado del paquete)");
            return;
        }

        if (puntos > 0) {
            Cliente titular = reserva.obtenerTitular();
            if (titular.canjearPuntos(puntos)) {
                reserva.setDescuentoPuntos(puntos * Reserva.VALOR_PUNTO);
                JOptionPane.showMessageDialog(this, "Se canjearon " + puntos + " puntos = S/ "
                        + String.format("%.2f", puntos * Reserva.VALOR_PUNTO) + " de descuento");
            } else {
                JOptionPane.showMessageDialog(this, "El titular no tiene puntos suficientes. Se creo la reserva sin canje.");
            }
        }

        JOptionPane.showMessageDialog(this, "Reserva " + reserva.getCodigo() + " creada.\n"
                + "Precio total: S/ " + String.format("%.2f", reserva.calcularPrecioTotal())
                + "\nPago minimo para confirmar: S/ " + String.format("%.2f", reserva.calcularPagoMinimo()));

        mostrarVoucher(reserva);
        mostrarInformacionPaquete();
        limpiar();
    }

    private void mostrarVoucher(Reserva reserva) {
        javax.swing.JTextArea area = new javax.swing.JTextArea(reserva.generarVoucher());
        area.setEditable(false);
        area.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 12));
        javax.swing.JScrollPane scroll = new javax.swing.JScrollPane(area);
        scroll.setPreferredSize(new java.awt.Dimension(480, 420));
        JOptionPane.showMessageDialog(this, scroll, "Voucher de Reserva", JOptionPane.INFORMATION_MESSAGE);
    }

    private void limpiar() {
        totalSeleccionados = 0;
        clientesSeleccionados = new Cliente[20];
        modeloLista.clear();
        txtAdultos.setText("");
        txtMenores.setText("");
        txtPuntosCanje.setText("0");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JLabel lblPaquete;
    private javax.swing.JComboBox<String> cboPaquete;
    private javax.swing.JLabel lblDocumento;
    private javax.swing.JTextField txtDocumentoCliente;
    private javax.swing.JLabel lblAdultos;
    private javax.swing.JTextField txtAdultos;
    private javax.swing.JLabel lblMenores;
    private javax.swing.JTextField txtMenores;
    private javax.swing.JLabel lblPuntos;
    private javax.swing.JTextField txtPuntosCanje;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblInformacion;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JLabel lblGrupo;
    private javax.swing.JScrollPane scrLista;
    private javax.swing.JList<String> lstClientes;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton btnCrearReserva;
    private javax.swing.JButton btnLimpiar;
    // End of variables declaration//GEN-END:variables
}
